Amir@132.148.134.86:3306

-- GRANT ALL PRIVILEGES

CREATE USER 'Amir'@'localhost' IDENTIFIED BY 'AmirScottAnderson)(^6385?';
GRANT ALL PRIVILEGES ON *.* TO 'Amir'@'localhost' WITH GRANT OPTION;
CREATE USER 'Amir'@'%' IDENTIFIED BY 'AmirScottAnderson)(^6385?';
GRANT ALL PRIVILEGES ON *.* TO 'Amir'@'%' WITH GRANT OPTION;

-- RESTRICT PRIVILEGES TO SPECIFIC DATABASE ONLY
CREATE USER 'Amir'@'localhost' IDENTIFIED BY 'AmirScottAnderson)(^6385?';
GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP ON HJ.* TO 'Amir'@'localhost';
CREATE USER 'Amir'@'%' IDENTIFIED BY 'AmirScottAnderson)(^6385?';
GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP ON HJ.* TO 'Amir'@'%';

